config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/auth/google_oauth2/callback', to: 'sessions#omni'
  get '/search', to: 'tasks#search'
  get 'login', to: 'sessions#new'
  get 'signup', to: 'employees#new'

  resources :contact_messages, only: [:new, :create]

  resources :lists do
    resources :tasks, only: [:index, :show, :new]
  end
  
  resources :employees, except: [:new] do 
    resources :tasks, only: [:index]
  end

  resources :tasks, only: [:index, :edit, :create, :update, :destroy]

  resources :sessions, only: [:create, :destroy]

end

app/models/employee.rb
class Employee < ApplicationRecord
 
  has_many :tasks
  has_many :lists, through: :tasks

  has_secure_password

  validates :name, :email, :password, presence: true
  validates :email, uniqueness: true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

    before_action :logged_in?, only: [:index, :show, :edit, :destroy]
    before_action :find_employee, only: [:show, :edit, :update, :destroy]

    def index 
        @employees = Employee.all
    end

    def show 
        
    end

    def new 
        @employee = Employee.new
    end

    def edit 

    end

    def create 
        @employee = Employee.new(employee_params)
        if @employee.save
            session[:user_id] = @employee.id
            redirect_to employee_path(@employee), notice: "Thank you for signing up!"
        else
            render 'new'
        end
     
    end

    def update 
        if helpers.current_user == @employee && @employee.update(employee_params)
            redirect_to employee_path(@employee)
        else
            redirect_to employee_path(helpers.current_user), alert: "You do not have permission to edit this account"
        end
    end

    def destroy 
        if helpers.current_user == @employee
            session.delete :user_id
            @employee.destroy
            redirect_to root_path
        else
            redirect_to employee_path(helpers.current_user), alert: "You do not have permission to delete this account"
        end
    end

    private

    def find_employee
        redirect_to root_path, alert: "Employee not found!" unless @employee = Employee.find_by(id: params[:id])
    end

    def employee_params 
        params.require(:employee).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>

    <%= f.label :name %><br>
    <%= f.text_field :name %>

    <br>

    <%= f.label :email %><br>
    <%= f.email_field :email %>

    <br>

    <%= f.label :password %><br>
    <%= f.password_field :password %>

    <br>

    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>

    <br><br>

    <%= f.submit %>

<% end %>

app/views/employees/edit.html.erb
<%= render partial: 'shared/errors', locals: {model: @employee} %>

<h3>Edit Employee Information Here:</h3>

<%= render 'form' %>

<br>

<%= link_to "Back", employee_path(current_user) %>

app/views/employees/index.html.erb
<h3>Here Is A List Of All Employees:</h3>

<hr>

<% @employees.each do |e| %>
    <strong>Employee Name: </strong><%= e.name %> - <strong>Employee Email: </strong><%= e.email %>
    <br>
<% end %>

<%= form_tag("/search", method: "get") do %>
    <%= label_tag(:q, "Search By Name:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
<% end  %>

app/views/employees/new.html.erb
<%= render partial: 'shared/errors', locals: {model: @employee} %>

<h3>Sign Up As A New Employee Here:</h3>

<%= render 'form' %>

app/views/employees/show.html.erb
<%= link_to "Edit Your Info", edit_employee_path(@employee) %> | <%= link_to "Delete Your Account", employee_path(@employee), method: :delete,
              data: { confirm: 'Are you sure?' } %>
<br>

<h3>Welcome <%= @employee.name %>,</h3> 
<h4>Here Are The Lists That Have Tasks Assigned To You:</h4>

<hr>

<% @employee.lists.group(:id).each do |l| %>

    <%= link_to l.normalize_name, list_tasks_path(l) %><br>
    
<% end %>