config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/auth/google_oauth2/callback', to: 'sessions#omni'
  get '/search', to: 'tasks#search'
  get 'login', to: 'sessions#new'
  get 'signup', to: 'employees#new'

  resources :contact_messages, only: [:new, :create]

  resources :lists do
    resources :tasks, only: [:index, :show, :new]
  end
  
  resources :employees, except: [:new] do 
    resources :tasks, only: [:index]
  end

  resources :tasks, only: [:index, :edit, :create, :update, :destroy]

  resources :sessions, only: [:create, :destroy]

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  belongs_to :employee, optional: true

  before_validation :normalize_title, :normalize_content, :normalize_address, on: [:create, :update]
  
  validates :title, :address, :content, presence: true

  scope :most_recent, -> {Task.order("created_at DESC").limit(5)}
  scope :tasks_by_employee,  ->(name) {Task.where("employee_id == ?", name)}
  scope :incomplete_tasks, -> {Task.where("completed == ?", false)}

  private 

  def normalize_title 
    self.title = title.titlecase 
  end

  def normalize_content 
    self.content = content.capitalize 
  end

  def normalize_address 
    self.address = address.titlecase 
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    before_action :logged_in?
    before_action :find_task, only: [:show, :update]
    before_action :can_edit_or_complete, only: [:edit, :destroy]
    rescue_from ActiveRecord::RecordNotFound, with: :invalid_list

    def index 
        if params[:list_id].present?
            find_list
            @tasks = @list.tasks
        else
            @tasks = Task.most_recent
        end
        render layout: "list_tasks"
    end

    def search
        emp = Employee.find_by(name: params[:q])
        @tasks = Task.tasks_by_employee(emp).incomplete_tasks
    end

    def show
    end

    def new 
        find_list
        @task = @list.tasks.build
    end

    def edit 
    end

    def create 
        @task = Task.new(task_params)
        if @task.save
            redirect_to list_tasks_path(@task.list)
        else
            render 'new'
        end
    end

    def update 
        if @task.update(task_params)
            redirect_to list_tasks_path(@task.list)
        else
            render 'edit'
        end
    end

    def destroy 
        list = @task.list
        @task.destroy
        redirect_to list_tasks_path(list)
    end

    private 

    def task_params 
        params.require(:task).permit(:title, :content, :list_id, :completed, :address, :employee_id)
    end

    def find_task 
        redirect_to lists_path, alert: "Task not found!" unless @task = Task.find_by(id: params[:id])
    end

    def find_list
        @list = List.find(params[:list_id])
    end

    def authorized
        helpers.current_user.name == @task.list.created_by || helpers.current_user == @task.employee
    end

    def can_edit_or_complete
        find_task
        redirect_to list_tasks_path(@task.list), alert: "You do not have the permissions to edit this task" unless !!authorized
    end

    def invalid_list
        logger.error "Attempt to access invalid list #{params[:list_id]}" 
        redirect_to lists_path, alert: 'Invalid list'
    end
    
end

app/helpers/tasks_helper.rb
module TasksHelper
    def check_task_complete 
        @task.completed ? "Completed" : "Incomplete"
    end

    def check_if_task_assigned
        if @task.employee != nil
            @task.employee.name
        else
            "Task Is Not Assigned!"
        end
    end

end

app/views/tasks/_form.html.erb
<%= render partial: 'shared/errors', locals: {model: @task} %>

<br>

<%= form_for(@task) do |f| %>

  <%= f.hidden_field :list_id, value: @task.list %>

  <%= f.label :title, "Enter The Title For This Task:" %><br>
  <%= f.text_field :title %>

  <br><br>

  <%= f.label :address, "Enter The Address For This Task:" %><br>
  <%= f.text_field :address %>

  <br><br>

  <%= f.label :content, "Enter The Details For This Task:" %><br>
  <%= f.text_area :content, size: "50x3" %>

  <br><br>

  <%= f.label :completed, "Mark As Completed or Incomplete:" %><br>
  <%= f.select(:completed, [["Completed", true], ["Incomplete", false]]) %>

  <br><br>

  <%= f.label :list_id, "Move Task To A Different List:" %><br>
  <%= f.collection_select :list_id, List.all, :id, :normalize_name %>

  <br><br>

  <%= f.label :employee_id, "Assign This Task To An Employee:" %><br>
  <%= f.collection_select :employee_id, Employee.all, :id, :name, {:prompt => "Select Employee"} %>

  <br><br>

  <%= f.submit %>

<% end %>

app/views/tasks/_task_completed.html.erb
<% tasks.each do |t| %>

    <% if t.completed == false %>
        <% if t.employee == current_user %>
            <strong><li style="color:red;"><%= t.title %> - <%= link_to "View Task Details", list_task_path(t.list, t) %></li></strong><br>
        <% else %>
            <li style="color:red;"><%= t.title %> - <%= link_to "View Task Details", list_task_path(t.list, t) %></li><br>
        <% end %>
    <% else t.completed == true %>
        <% if t.employee == current_user %>
            <strong><li style="color:green;"><%= t.title %> - <%= link_to "View Task Details", list_task_path(t.list, t) %></li></strong><br>
        <% else %>
            <li style="color:green;"><%= t.title %> - <%= link_to "View Task Details", list_task_path(t.list, t) %></li><br>
        <% end %>
    <% end %>
                
<% end %>

app/views/tasks/edit.html.erb
<h3>Edit This Task:</h3>

<br>

<%= render "form" %>

<br>

<%= link_to "Back", list_task_path(@task.list, @task) %>

app/views/tasks/index.html.erb
<% if @list %>

    <%= link_to "Add A Task To This List", new_list_task_path(@list) %> | <%= link_to "Edit This List", edit_list_path(@list) %> | <%= link_to "Delete This List", list_path(@list), method: :delete,
              data: { confirm: 'Are you sure?' } %>

    <br>

    <h3><%= @list.normalize_name %></h3>

    This list was created by: <%= @list.created_by %><br><br>

    * Tasks in bold are assigned to you *

    <hr>
                
<% else %>

    <h3>Here are the 5 most recently added tasks:</h3>

    <hr>

<% end %>
 
    <%= render partial: "task_completed", locals: {tasks: @tasks} %>

<br>

    <%= link_to "Back", lists_path %>

app/views/tasks/new.html.erb
<h3>Add A New Task To This List:</h3>

<br>

<%= render "form" %>

<br>

<%= link_to "Back", list_tasks_path(@task.list) %>

app/views/tasks/search.html.erb
<%= render partial: "task_completed", locals: {tasks: @tasks} %>

app/views/tasks/show.html.erb
<%= link_to "Edit This Task", edit_task_path(@task) %> | <%= link_to "Delete This Task", task_path(@task), method: :delete,
              data: { confirm: 'Are you sure?' } %>

<br>

<h3><%= @task.title %></h3>

<strong>Task Status: </strong>

    <%= check_task_complete %>

<br>

<strong>Task Address: </strong><%= @task.address %>

<br>

<strong>Assigned to: </strong><%= check_if_task_assigned %>

    
<br><hr>

<strong>Details:</strong> <%= @task.content %>

<br><br>

<%= link_to "Back", list_tasks_path(@task.list) %>