config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/auth/google_oauth2/callback', to: 'sessions#omni'
  get '/search', to: 'tasks#search'
  get 'login', to: 'sessions#new'
  get 'signup', to: 'employees#new'

  resources :contact_messages, only: [:new, :create]

  resources :lists do
    resources :tasks, only: [:index, :show, :new]
  end
  
  resources :employees, except: [:new] do 
    resources :tasks, only: [:index]
  end

  resources :tasks, only: [:index, :edit, :create, :update, :destroy]

  resources :sessions, only: [:create, :destroy]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Fox Services
  </small>
  <nav>
    <ul>
      <% if is_logged_in? %>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", new_contact_message_path %></li>
        <li><%= link_to "Help", help_path %></li>
      <% end %>
      <li><a href="https://www.facebook.com/foxservices82/?__tn__=HHH-R">Facebook</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
  <%= link_to "Fox Services", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <% if is_logged_in? %>
        <li><%= link_to "My Tasks", employee_path(current_user) %></li>
        <li><%= link_to "Task Lists", lists_path %></li>
        <li><%= link_to "New Task List", new_list_path %></li>
        <li><%= link_to "Most Recent Tasks", tasks_path %></li>
        <li><%= link_to "View All Employees", employees_path %></li>
        <li><%= link_to "Log Out", session_path(:user_id), method: :delete %></li>
      <% else %>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", new_contact_message_path %></li>
        <li><%= link_to "Help", help_path %></li>
      <% end %>
      </ul>
    </nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= yield(:title) %> | Fox Services |</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">

      <div class="center jumbotron" style="opacity: 0.95;">

        <div style="color:red;">
          <%= flash_alert %>
        </div>

        <div style="color:green;">
          <%= flash_notice %>
        </div>

        <%= yield %>

      </div>
      
    </div>
      
      <div class="container">
        <%= render 'layouts/footer' %>
      </div>

  </body>
</html>

app/views/layouts/list_show.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= yield(:title) %> | Fox Services |</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <%= render 'layouts/header' %>

      <div class="container">

        <div class="center jumbotron" style="opacity: 0.95; height: 500px; overflow-x: hidden; overflow-x: auto; text-align:center;">

          <div style="color:red;">
            <% if flash[:alert] %>
              <%= flash[:alert] %>
            <% end %>
          </div>

        <%= yield %>

        </div>

      </div>

      <div class="container">
        <%= render 'layouts/footer' %>
      </div>

  </body>
</html>

app/views/layouts/list_tasks.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= yield(:title) %> | Fox Services |</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <%= render 'layouts/header' %>

      <div class="container">

        <div class="center jumbotron" style="opacity: 0.95; height: 500px; overflow-x: hidden; overflow-x: auto; text-align:center;">

          <div style="color:red;">
            <%= flash_alert %>
          </div>

        <%= yield %>

        </div>

      </div>

      <div class="container">
        <%= render 'layouts/footer' %>
      </div>

  </body>
</html>